# Generated by Django 2.1.4 on 2019-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='个人介绍'),
        ),
    ]
