# Generated by Django 2.1.4 on 2019-01-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userinfo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='群简介'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(blank=True, default='这个人很懒，什么都没留下', max_length=64, null=True, verbose_name='个人介绍'),
        ),
    ]
