# Generated by Django 2.1.4 on 2019-01-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190104_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='群简介'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='群名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='desc',
            field=models.CharField(blank=True, default='这个人很懒，什么都没留下', max_length=30, null=True, verbose_name='个人介绍'),
        ),
    ]
