# Generated by Django 2.1.4 on 2019-01-07 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190104_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='_userinfo_friend_+', to=settings.AUTH_USER_MODEL, verbose_name='好友'),
        ),
    ]
