# Generated by Django 2.1.4 on 2019-01-07 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20190107_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatgroup',
            options={'verbose_name': '聊天房间', 'verbose_name_plural': '聊天房间'},
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='房间简介'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='join_groups', to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(max_length=30, verbose_name='房间名'),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to=settings.AUTH_USER_MODEL, verbose_name='房间创建者'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_type',
            field=models.CharField(choices=[('group', '组消息'), ('single', '个人消息')], default='group', max_length=6, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='friend',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='好友'),
        ),
    ]
