# Generated by Django 2.1.4 on 2019-01-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20190107_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='desc',
            field=models.CharField(default='这个群主很懒，什么也没写', max_length=60, verbose_name='房间简介'),
        ),
    ]
