# Generated by Django 2.1.4 on 2019-01-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='channel_name',
            field=models.CharField(default=None, max_length=50, verbose_name='通道名字'),
        ),
    ]
