# Generated by Django 2.1.4 on 2019-01-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_userinfo_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='channel_name',
        ),
    ]
